[
  {
    "ShippingLatitude": null,
    "LastModifiedDate": "2024-01-22T19:03:58.000Z",
    "BillingCity": "Hyderabad",
    "JigsawCompanyId": null,
    "SLA__c": null,
    "type": "Account",
    "NaicsCode": null,
    "Name": "Test",
    "Industry": null,
    "CreatedById": "0055g00000C1r1KAAR",
    "OperatingHoursId": null,
    "TickerSymbol": null,
    "BillingGeocodeAccuracy": null,
    "AccountSource": null,
    "BillingPostalCode": "500089",
    "DandbCompanyId": null,
    "PhotoUrl": "/services/images/photo/0015g00001aoo4wAAA",
    "MasterRecordId": null,
    "IsDeleted": "false",
    "LastViewedDate": "2024-01-22T18:58:58.000Z",
    "ShippingGeocodeAccuracy": null,
    "DunsNumber": null,
    "Sic": null,
    "ShippingStreet": "Random Street",
    "CleanStatus": "Pending",
    "ShippingPostalCode": "600089",
    "YearStarted": null,
    "CreatedDate": "2024-01-22T18:50:11.000Z",
    "CustomerPriority__c": null,
    "email__c": "def@xyz.com",
    "ShippingState": "Karnataka",
    "Id": "0015g00001aoo4wAAA",
    "SicDesc": null,
    "BillingState": "Telangana",
    "AnnualRevenue": null,
    "Jigsaw": null,
    "Active__c": null,
    "Site": null,
    "Ownership": null,
    "Description": null,
    "Rating": null,
    "Website": null,
    "LastReferencedDate": "2024-01-22T18:58:58.000Z",
    "BillingLatitude": null,
    "NumberOfEmployees": null,
    "BillingAddress": {
      "country": "USA",
      "city": "Hyderabad",
      "countryCode": null,
      "street": "High Street",
      "latitude": null,
      "postalCode": "500089",
      "geocodeAccuracy": null,
      "stateCode": null,
      "state": "Telangana",
      "longitude": null
    },
    "OwnerId": "0055g00000C1r1KAAR",
    "SLASerialNumber__c": null,
    "BillingLongitude": null,
    "Tradestyle": null,
    "Phone": "903111234567",
    "NumberofLocations__c": null,
    "UpsellOpportunity__c": null,
    "ShippingCountry": "Australia",
    "ShippingCity": "Bangalore",
    "ParentId": null,
    "NaicsDesc": null,
    "AccountNumber": "1015",
    "SystemModstamp": "2024-01-22T19:03:58.000Z",
    "Type": null,
    "BillingCountry": "USA",
    "SLAExpirationDate__c": null,
    "BillingStreet": "High Street",
    "ShippingAddress": {
      "country": "Australia",
      "city": "Bangalore",
      "countryCode": null,
      "street": "Random Street",
      "latitude": null,
      "postalCode": "600089",
      "geocodeAccuracy": null,
      "stateCode": null,
      "state": "Karnataka",
      "longitude": null
    },
    "LastActivityDate": null,
    "Fax": "21312312",
    "LastModifiedById": "0055g00000C1r1KAAR",
    "ShippingLongitude": null
  }
]