https:
  port: "8082"
salesforce:
  username: ""
  consumerKey: ""
  tokenUrl: "https://login.salesforce.com/services/oauth2/token"
  accountQuery: "SELECT id,AccountNumber,BillingCity,BillingCountry,BillingPostalCode,BillingState,BillingStreet,Fax,Name,Phone,email__c,ShippingCity,ShippingCountry,ShippingPostalCode,ShippingState,ShippingStreet FROM Account WHERE id=:id LIMIT 100"
  accountCountQuery: "SELECT FIELDS(ALL) FROM Account WHERE id=:id"
maxRetries: "3"
timeBetweenRetries: "1000"
keystore:
  path: "certs/sf-accounts-sapi.p12"
  alias: "server"
common:  
  notifications:
    send: "none"
    email:      
      from-address: "noreply@invalid.com"      
      to-address: "nodest@invalid.com"
    sms:      
      from-number: "18005551234"      
      to-number: "18005551234"