{
  "headers": {
    "client_id": "test",
    "client_secret": "test",
    "correlationid": "localTest",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.36.1",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "2bbfb944-b75f-4f44-a3b0-2e7f25e88637",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "471"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/accounts",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/accounts",
  "listenerPath": "/api/*",
  "relativePath": "/api/accounts",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/accounts",
  "rawRequestPath": "/api/accounts",
  "remoteAddress": "/127.0.0.1:62676",
  "requestPath": "/api/accounts"
}