https:
  port: "8082"
country-lookup:
  host: "api.first.org"
  url: "/data/v1/countries"
  port: "443"
os:
  countryPayloadKey: "countryPayload"
common:  
  notifications:
    send: "none"
    email:      
      from-address: "noreply@invalid.com"      
      to-address: "nodest@invalid.com"
    sms:      
      from-number: "18005551234"      
      to-number: "18005551234"
